name: CI

on:
  push:
    paths-ignore:
      - README.md
      - 'docs/**'
  pull_request:

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.12.0]         # October 7, 2025
        julia-arch: [x64]
        os: [ubuntu-latest]
        include:
          - julia-version: nightly
            os: ubuntu-latest
          - julia-version: 1.11.7       # 2025-09-15
            os: ubuntu-latest
          - julia-version: 1.6.7        # 2022-07-20
            os: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
    - uses: julia-actions/cache@v1
    - uses: julia-actions/julia-buildpkg@v1
    - uses: julia-actions/julia-runtest@v1

  Coverage:
    needs: Test
    if: github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
